FEW_SHOT_EN = (
    "Use the following context to help answer the question.\n\nCONTEXT:\n{context}\n\n"
    "Answer with the most concise factual response possible — a short phrase "
    "or a few words only. No sentences, no explanations. "
    "Give your response in English regardless of the language of the question.\n"
    "Q: When did World War 2 start and end?\n"
    "A: Sep 1, 1939 – Sep 2, 1945\n"
    "Q: Who invented the telephone?\n"
    "A: Alexander Graham Bell\n"
    "Q: What is the capital of Japan?\n"
    "A: Tokyo\n"
    "Q: When did the Berlin Wall fall?\n"
    "A: November 9, 1989\n"
    "Q: {question}\n"
    "A:"
)


_FEW_SHOT_LANG: dict[str, str] = {
    "ar": (
        "استخدم السياق التالي للمساعدة في الإجابة على السؤال.\n\nالسياق:\n{context}\n\n"
        "أجب بأقصر إجابة واقعية ممكنة — عبارة قصيرة أو كلمات قليلة فقط. "
        "لا جمل، لا شرح. أعطِ إجابتك باللغة العربية.\n"
        "Q: متى بدأت الحرب العالمية الثانية وانتهت؟\n"
        "A: 1 سبتمبر 1939 – 2 سبتمبر 1945\n"
        "Q: من اخترع الهاتف؟\n"
        "A: ألكسندر غراهام بيل\n"
        "Q: ما عاصمة اليابان؟\n"
        "A: طوكيو\n"
        "Q: متى سقط جدار برلين؟\n"
        "A: 9 نوفمبر 1989\n"
        "Q: {question}\n"
        "A:"
    ),
    "bn": (
        "নিচের প্রসঙ্গটি ব্যবহার করে প্রশ্নের উত্তর দিন।\n\nপ্রসঙ্গ:\n{context}\n\n"
        "যতটা সম্ভব সংক্ষিপ্ত তথ্যভিত্তিক উত্তর দিন — একটি ছোট বাক্যাংশ বা কয়েকটি শব্দ। "
        "কোনো বাক্য বা ব্যাখ্যা নয়। বাংলায় উত্তর দিন।\n"
        "Q: দ্বিতীয় বিশ্বযুদ্ধ কখন শুরু ও শেষ হয়েছিল?\n"
        "A: ১ সেপ্টেম্বর ১৯৩৯ – ২ সেপ্টেম্বর ১৯৪৫\n"
        "Q: টেলিফোন কে আবিষ্কার করেছিলেন?\n"
        "A: আলেকজান্ডার গ্রাহাম বেল\n"
        "Q: জাপানের রাজধানী কী?\n"
        "A: টোকিও\n"
        "Q: বার্লিন ওয়াল কখন পড়েছিল?\n"
        "A: ৯ নভেম্বর ১৯৮৯\n"
        "Q: {question}\n"
        "A:"
    ),
    "fi": (
        "Käytä seuraavaa kontekstia apuna vastaamisessa.\n\nKONTEKSTI:\n{context}\n\n"
        "Vastaa mahdollisimman lyhyesti ja ytimekkäästi — lyhyt lauseke tai muutama sana riittää. "
        "Ei kokonaisia lauseita, ei selityksiä. Vastaa suomeksi.\n"
        "Q: Milloin toinen maailmansota alkoi ja päättyi?\n"
        "A: 1. syyskuuta 1939 – 2. syyskuuta 1945\n"
        "Q: Kuka keksi puhelimen?\n"
        "A: Alexander Graham Bell\n"
        "Q: Mikä on Japanin pääkaupunki?\n"
        "A: Tokio\n"
        "Q: Milloin Berliinin muuri murtui?\n"
        "A: 9. marraskuuta 1989\n"
        "Q: {question}\n"
        "A:"
    ),
    "ja": (
        "以下のコンテキストを参考にして質問に答えてください。\n\nコンテキスト:\n{context}\n\n"
        "できるだけ簡潔な事実に基づく回答をしてください — 短いフレーズまたは数語のみ。"
        "文章や説明は不要です。日本語で回答してください。\n"
        "Q: 第二次世界大戦はいつ始まり、いつ終わりましたか？\n"
        "A: 1939年9月1日 〜 1945年9月2日\n"
        "Q: 電話を発明したのは誰ですか？\n"
        "A: アレクサンダー・グラハム・ベル\n"
        "Q: 日本の首都はどこですか？\n"
        "A: 東京\n"
        "Q: ベルリンの壁が崩壊したのはいつですか？\n"
        "A: 1989年11月9日\n"
        "Q: {question}\n"
        "A:"
    ),
    "ko": (
        "다음 맥락을 참고하여 질문에 답하세요.\n\n맥락:\n{context}\n\n"
        "가능한 한 간결하고 사실에 근거한 답변을 해주세요 — 짧은 구절이나 몇 단어만으로. "
        "문장이나 설명은 필요 없습니다. 한국어로 답변해 주세요.\n"
        "Q: 제2차 세계대전은 언제 시작되고 끝났나요?\n"
        "A: 1939년 9월 1일 – 1945년 9월 2일\n"
        "Q: 전화기를 발명한 사람은 누구인가요?\n"
        "A: 알렉산더 그레이엄 벨\n"
        "Q: 일본의 수도는 어디인가요?\n"
        "A: 도쿄\n"
        "Q: 베를린 장벽은 언제 붕괴되었나요?\n"
        "A: 1989년 11월 9일\n"
        "Q: {question}\n"
        "A:"
    ),
    "ru": (
        "Используйте следующий контекст для ответа на вопрос.\n\nКОНТЕКСТ:\n{context}\n\n"
        "Отвечайте максимально кратко и по существу — короткой фразой или несколькими словами. "
        "Никаких предложений, никаких объяснений. Отвечайте на русском языке.\n"
        "Q: Когда началась и закончилась Вторая мировая война?\n"
        "A: 1 сентября 1939 – 2 сентября 1945\n"
        "Q: Кто изобрёл телефон?\n"
        "A: Александер Грэм Белл\n"
        "Q: Какова столица Японии?\n"
        "A: Токио\n"
        "Q: Когда пала Берлинская стена?\n"
        "A: 9 ноября 1989 года\n"
        "Q: {question}\n"
        "A:"
    ),
    "te": (
        "క్రింది సందర్భాన్ని ఉపయోగించి ప్రశ్నకు సమాధానం ఇవ్వండి.\n\nసందర్భం:\n{context}\n\n"
        "వీలైనంత సంక్షిప్తంగా వాస్తవ ఆధారిత సమాధానం ఇవ్వండి — ఒక చిన్న పదబంధం లేదా కొన్ని పదాలు మాత్రమే. "
        "వాక్యాలు వద్దు, వివరణలు వద్దు. తెలుగులో సమాధానం ఇవ్వండి.\n"
        "Q: రెండవ ప్రపంచ యుద్ధం ఎప్పుడు ప్రారంభమై ముగిసింది?\n"
        "A: 1 సెప్టెంబర్ 1939 – 2 సెప్టెంబర్ 1945\n"
        "Q: టెలిఫోన్‌ను ఎవరు కనుగొన్నారు?\n"
        "A: అలెగ్జాండర్ గ్రాహం బెల్\n"
        "Q: జపాన్ రాజధాని ఏది?\n"
        "A: టోక్యో\n"
        "Q: బెర్లిన్ గోడ ఎప్పుడు కూలిపోయింది?\n"
        "A: నవంబర్ 9, 1989\n"
        "Q: {question}\n"
        "A:"
    ),
}